### ISSUE TITLE
Missing steps in the conversion script

### ISSUE THREAD

**Issue by ghost** [lmaxwell/gmmVoiceConversion#1]
I've tried to run this script, but the script needed to convert the wav files in lf0, mcep and raw files is missing, and the vc_cd command is not present in SPTK (so far I've tried only version 3.9).

**Comment by lmaxwell** [comment]
sorry, this code focus on voice conversion, so feature extraction is not included. You can use HTS Toolkit [http://hts.sp.nitech.ac.jp/?Download]  to extract features(lf0,mcep). You also may need to modify config.sh( MGCORDER etc..) depending on you feature.

vc_cd is my modification of SPTK's vc command, because vc is too slow, I have summited a patch to SPTK , however, they have not merged it yet.  vc_cd works the same as vc, so you can vc, they get the same result.

**Comment by ghost** [comment]
Thanks! I have used the HTS demo and looks like it is going to work.
